name: Tests

on:
  push:
    branches:
      - main


jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Test Setup
      run: |
        python -m pip install -r requirements.txt -r test-requirements.txt
        python -m pip install tox
    - name: Run Tests
      run: tox -e py
      env:
        GRETEL_API_KEY: ${{ secrets.GRETEL_TEST_API_KEY }}

  style-checks:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Test Setup
      run: |
        python -m pip install -r requirements.txt -r test-requirements.txt
        python -m pip install tox flake8
    - name: flake8
      run: tox -e flake8
